### PR TITLE
Fix/pipes with redirects

### LINKED ISSUE #52: update parser
- the parser can't manage complex shell-inputs for now, so need to update this.
  - several pipes
    - builtin
    - not builtin <- done!
  - several redirects
  - some other pattern...

### LINKED ISSUE #64: pipe commands with redirect will fail
- the commands such like `cat < file1 | cat > file2` would fail because of bug of handling file descriptors

### PR DESCRIPTION
**Pull request by cheedah**
- some refactoring
- handle `cat < file1 | cat > file2` pattern

### CODE REVIEW

File: srcs/execute/execute.c [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+		state->process_count++;
+		state->pids[state->process_count - 1] = pid;
+		i = 0;
+		while (i < state->redirect_num)
+		{
+			if (state->redirects[i]->file_fd != -1)
+				close(state->redirects[i]->file_fd);
+			i++;
+		}
+		state->redirect_num = 0;
```
Comment (cheedah) [inline srcs/execute/execute.c:76]: これ

**Comment by Hiroaki-K4** [comment]
LGTM

**Review by Hiroaki-K4 — APPROVED** [review]
LGTM
